### ISSUE TITLE
Error: global leak(s) detected

### ISSUE THREAD

**Issue by ziegfiroyt** [aelbore/vite-plugin-test#1]
Hello,
I run `yarn test` on your Vue example, than "renders" case is passing, but it returns `global leak(s) detected` error at the same time.
Why and how can we fix this leak? 
Thank you so much!

<img width="422" alt="Screen Shot 2021-03-21 at 04 54 16" src="https://user-images.githubusercontent.com/266607/111891135-7f48a600-8a01-11eb-9c8e-e8145bc6535d.png">

**Comment by ziegfiroyt** [comment]
Adding `m.setup({ checkLeaks: false})` into **aria-mocha** solves leak error, but is it a good way, I don't know :)

**Comment by aelbore** [comment]
@ziegfiroyt thanks for creating this issue. 
yes you are right, i remove the the `mocha.checkLeaks()` in `index.html` which same as what you suggested. 
you can try it with update code in master branch. then let me know if resolve the issue i will publish new version of plugin.

**Comment by ziegfiroyt** [comment]
i've tried your changes and yes, it works perfectly! thank you so much @aelbore

**Comment by ziegfiroyt** [comment]
hello, can you release a new version, please? @aelbore

**Comment by aelbore** [comment]
yes i did you can check version 0.0.5 let me know if you have issues thanks 👍
